/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as BuyIdRouteImport } from './routes/buy.$id'
import { Route as AgentSellRouteImport } from './routes/agent.sell'
import { Route as BuyIdInspectionRouteImport } from './routes/buy.$id.inspection'
import { Route as BuyIdDefectsRouteImport } from './routes/buy.$id.defects'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIdRoute = BuyIdRouteImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSellRoute = AgentSellRouteImport.update({
  id: '/agent/sell',
  path: '/agent/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIdInspectionRoute = BuyIdInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => BuyIdRoute,
} as any)
const BuyIdDefectsRoute = BuyIdDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => BuyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/agent/sell': typeof AgentSellRoute
  '/buy/$id': typeof BuyIdRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/buy/$id/defects': typeof BuyIdDefectsRoute
  '/buy/$id/inspection': typeof BuyIdInspectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/agent/sell': typeof AgentSellRoute
  '/buy/$id': typeof BuyIdRouteWithChildren
  '/agent': typeof AgentIndexRoute
  '/buy': typeof BuyIndexRoute
  '/buy/$id/defects': typeof BuyIdDefectsRoute
  '/buy/$id/inspection': typeof BuyIdInspectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/agent/sell': typeof AgentSellRoute
  '/buy/$id': typeof BuyIdRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/buy/$id/defects': typeof BuyIdDefectsRoute
  '/buy/$id/inspection': typeof BuyIdInspectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/sell'
    | '/support'
    | '/verify-otp'
    | '/agent/sell'
    | '/buy/$id'
    | '/agent/'
    | '/buy/'
    | '/buy/$id/defects'
    | '/buy/$id/inspection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/sell'
    | '/support'
    | '/verify-otp'
    | '/agent/sell'
    | '/buy/$id'
    | '/agent'
    | '/buy'
    | '/buy/$id/defects'
    | '/buy/$id/inspection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/sell'
    | '/support'
    | '/verify-otp'
    | '/agent/sell'
    | '/buy/$id'
    | '/agent/'
    | '/buy/'
    | '/buy/$id/defects'
    | '/buy/$id/inspection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SellRoute: typeof SellRoute
  SupportRoute: typeof SupportRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AgentSellRoute: typeof AgentSellRoute
  BuyIdRoute: typeof BuyIdRouteWithChildren
  AgentIndexRoute: typeof AgentIndexRoute
  BuyIndexRoute: typeof BuyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$id': {
      id: '/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof BuyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/sell': {
      id: '/agent/sell'
      path: '/agent/sell'
      fullPath: '/agent/sell'
      preLoaderRoute: typeof AgentSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$id/inspection': {
      id: '/buy/$id/inspection'
      path: '/inspection'
      fullPath: '/buy/$id/inspection'
      preLoaderRoute: typeof BuyIdInspectionRouteImport
      parentRoute: typeof BuyIdRoute
    }
    '/buy/$id/defects': {
      id: '/buy/$id/defects'
      path: '/defects'
      fullPath: '/buy/$id/defects'
      preLoaderRoute: typeof BuyIdDefectsRouteImport
      parentRoute: typeof BuyIdRoute
    }
  }
}

interface BuyIdRouteChildren {
  BuyIdDefectsRoute: typeof BuyIdDefectsRoute
  BuyIdInspectionRoute: typeof BuyIdInspectionRoute
}

const BuyIdRouteChildren: BuyIdRouteChildren = {
  BuyIdDefectsRoute: BuyIdDefectsRoute,
  BuyIdInspectionRoute: BuyIdInspectionRoute,
}

const BuyIdRouteWithChildren = BuyIdRoute._addFileChildren(BuyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SellRoute: SellRoute,
  SupportRoute: SupportRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AgentSellRoute: AgentSellRoute,
  BuyIdRoute: BuyIdRouteWithChildren,
  AgentIndexRoute: AgentIndexRoute,
  BuyIndexRoute: BuyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
